OPKODABbl/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Helpers;
using OPKODABbl.Models.Account;
using OPKODABbl.Models.Forum;
using OPKODABbl.Service;
using OPKODABbl.ViewModels.Forum;

namespace OPKODABbl.Controllers
{
    public class ForumController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public ForumController(WebsiteContext websiteContext)
        {
            _websiteDB = websiteContext;
        }

        #region Главная страница форума
        public async Task<IActionResult> Index()
        {
            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            // Формируем список разделов в соответствии с уровнем доступа юзера, включая подраздела, последние темы и сообщения в нём
            List<Section> sections = await _websiteDB.Sections.Where(s => s.SectionAccessLevel <= userAccessLevel)
                                                              .Include(s => s.Subsections).ThenInclude(s => s.Topics).ThenInclude(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                              .OrderBy(s => s.SectionPosition).ToListAsync();

            // Придется прибегнуть к такому говнокоду для разгрузки страницы Index от кода рпи формировании
            foreach (var section in sections)
            {
                foreach (var subsection in section.Subsections)
                {
                    foreach (var topic in subsection.Topics)
                    {
                        // Упорядочиваем все ответы в теме по дате
                        topic.Replies = topic.Replies.OrderBy(r => r.ReplyDate).ToList();
                    }

                    // Упорядочиваем все темы в разделе по дате последнего ответа (ответы уже упорядочили выше)
                    subsection.Topics = subsection.Topics.OrderBy(t => t.Replies.Last().ReplyDate).ToList();
                }
            }

            // Передаем в представление
            return View(sections);
        }
        #endregion

        #region Просмотр подраздела форума
        public async Task<IActionResult> Subsection(Guid subsectionId, int page = 1)
        {
            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            // Формируем модель подраздела с проверкой уровня доступа, а так же со всеми темами, находящимися в подразделе и пр.
            Subsection subsection = await _websiteDB.Subsections.Where(s => s.Section.SectionAccessLevel <= userAccessLevel)
                                                                .Include(s => s.Topics).ThenInclude(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                                .FirstOrDefaultAsync(s => s.Id == subsectionId);

            // Проверяем существование подраздела в общем и для данного пользователя в частности (при недостатке прав он будет равен null)
            if (subsection != null)
            {
                // Берем настройки из БД
                SettingsForum settings = await _websiteDB.SettingsForum.FirstAsync();

                // Сортировка ответов в каждой теме по дате
                subsection.Topics.ForEach(t => t.Replies = t.Replies.OrderBy(r => r.ReplyDate).ToList());
                // Сортировка тем в подразделе по дате последнего ответа и разбив по страницам
                int count = subsection.Topics.Count();
                int subsectionPageSize = settings.SubsectionPageSize;
                int topicPageSize = settings.TopicPageSize;

                subsection.Topics = subsection.Topics.OrderByDescending(t => t.Announcement).ThenByDescending(t => t.Replies.Last().ReplyDate).Skip((page - 1) * subsectionPageSize).Take(subsectionPageSize).ToList();

                ViewBag.TotalPages = (int)Math.Ceiling(count / (double)subsectionPageSize);
                ViewBag.CurrentPage = page;
                ViewBag.TopicPageSize = topicPageSize;

                // Передаем в представление
                return View(subsection);
            }

            // Если такого раздела не существует или у пользователя нет прав на просмотр подраздела, отправляем ему ошибку 404
            return Redirect("/Main/PageNotFound");
        }
        #endregion

        #region Просмотр топика
        public async Task<IActionResult> ViewTopic(Guid topicId, int page = 1)
        {
            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            // Формируем модель топика со всеми ответами и пользователями в нём. И обязательно проверка на уровень доступа пользователя, для избежания неавторизованного просмотра по прямой ссылке
            Topic topic = await _websiteDB.Topics.Where(t => t.Subsection.Section.SectionAccessLevel <= userAccessLevel)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.AvatarImage)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.Role)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                 .Include(t => t.Subsection)
                                                 .FirstOrDefaultAsync(t => t.Id == topicId);

            // Если у юзера недостаточно прав для просмотра, то топик будет null
            if (topic != null)
            {
                topic.Views += 1;
                _websiteDB.Topics.Update(topic);
                await _websiteDB.SaveChangesAsync();

                // Берем настройки из БД
                SettingsForum settings = await _websiteDB.SettingsForum.FirstAsync();

                // Разбиваем ответы по страницам
                int count = topic.Replies.Count();
                int pageSize = settings.TopicPageSize;

                topic.Replies = topic.Replies.OrderBy(r => r.ReplyDate).Skip((page - 1) * pageSize).Take(pageSize).ToList();
                // Замена символов и ББ-код в каждом ответе
                topic.Replies.ForEach(r => r.ReplyBody = r.ReplyBody.Replace(r.ReplyBody, r.ReplyBody.SpecSymbolsToView().BbCode()));

                ViewBag.TotalPages = (int)Math.Ceiling(count / (double)pageSize);
                ViewBag.CurrentPage = page;

                return View(topic);
            }

            // Если топик не существует для пользователя, выводим сообщение об ошибке
            return Redirect("/Main/PageNotFound");
        }
        #endregion

        #region Создать топик[GET]
        [HttpGet]
        public async Task<IActionResult> CreateTopic(Guid subsectionId)
        {
            // Проверка, чтобы пользователь был авторизован
            if (User.Identity.IsAuthenticated)
            {
                // Формируем модель подраздела
                Subsection subsection = await _websiteDB.Subsections.Include(s => s.Section).FirstOrDefaultAsync(s => s.Id == subsectionId);

                // Проверяем, что такой подраздел существует
                if (subsection != null)
                {
                    ViewBag.SubsectionId = subsection.Id;
                    ViewBag.SubsectionName = subsection.SubsectionName;

                    // Формируем модель пользователя с уровнем доступа для проверки
                    User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);

                    // Проверяем, может ли пользователь просматривать данный подраздел
                    if (subsection.Section.SectionAccessLevel <= user.Role.AccessLevel)
                    {
                        // Если может, то возвращаем ему представление
                        //ViewBag.SubsectionId = subsection.Id;
                        return View();
                    }
                }

                // А если не может, то возвращаем ему ошибку 404
                return Redirect("/Main/PageNotFound");
            }

            // Если юзер не авторизован, перенаправляем его на страницу авторизации
            return RedirectToAction("Login", "Account");
        }
        #endregion

OPKODABbl/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Models.Gallery;
using OPKODABbl.Service;

namespace OPKODABbl.Controllers
{
    public class GalleryController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public GalleryController(WebsiteContext context)
        {
            _websiteDB = context;
        }

        #region Список галерей
        public async Task<IActionResult> Galleries()
        {
            List<Gallery> galleries = await _websiteDB.Galleries.Include(g => g.GalleryImages).OrderByDescending(g => g.GalleryDate).ToListAsync();

            ViewBag.Title = "Галерея";

            return View(galleries);
        }
        #endregion

        #region Просмотр галереи
        public async Task<IActionResult> ViewGallery(Guid galleryId)
        {
            Gallery gallery = await _websiteDB.Galleries.Include(g => g.GalleryImages).FirstOrDefaultAsync(g => g.Id == galleryId);

            if (gallery != null)
            {
                ViewBag.Title = gallery.GalleryTitle;

                gallery.GalleryImages = gallery.GalleryImages.OrderBy(i => i.ImageDate).ToList();

                // Урезание заголовка до 40 символов
                if (gallery.GalleryTitle.Length > 40)
                {
                    // Ограничиваем длину заголовка и всё что сверх меры - переносим на новую отдельную строку
                    string shortTitle = new string(gallery.GalleryTitle.Take(40).ToArray()) + "...";
                    string titleOverflow = "..." + new string(gallery.GalleryTitle.Skip(40).ToArray()) + "<br /><br />";

                    gallery.GalleryTitle = shortTitle;
                    gallery.GalleryDescription = titleOverflow + gallery.GalleryDescription;

                    // Возврат записи в преобразованном виде
                    return View(gallery);
                }

                // Или в изначальном виде
                return View(gallery);
            }

            return Redirect("/Main/PageNotFound");

        }
        #endregion

    }
}

OPKODABbl/Controllers/MainController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Helpers;
using OPKODABbl.Models.Account;
using OPKODABbl.Models.Forum;
using OPKODABbl.Models.Gallery;
using OPKODABbl.Models.Main;
using OPKODABbl.Service;
using OPKODABbl.ViewModels.Main;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OPKODABbl.Controllers
{
    public class MainController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public MainController(WebsiteContext websiteContext)
        {
            _websiteDB = websiteContext;
        }

        #region Главная страница
        public async Task<IActionResult> Index()
        {
            ViewBag.Title = "ОРКОДАВЫ";

            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            List<Topic> topics = await _websiteDB.Topics.Where(t => t.Subsection.Section.SectionAccessLevel <= userAccessLevel)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                 .Include(t => t.Subsection).ToListAsync();

            foreach (var topic in topics)
            {
                // Упорядочиваем все ответы в теме по дате
                topic.Replies = topic.Replies.OrderBy(r => r.ReplyDate).ToList();
                // удаляем bb-теги из первого сообщения для показа на главной
                topic.Replies.First().ReplyBody = topic.Replies.First().ReplyBody.DeleteTags();
            }
            // Упорядочиваем все темы в разделе по дате последнего ответа (ответы уже упорядочили выше)
            topics = topics.OrderByDescending(t => t.Replies.Last().ReplyDate).ToList();
            topics = topics.Take(5).ToList();

            List<News> news = await _websiteDB.News.Include(n => n.NewsImages).OrderByDescending(n => n.NewsDate).Take(3).ToListAsync();
            List<Gallery> galleries = await _websiteDB.Galleries.OrderByDescending(g => g.GalleryDate).Take(3).ToListAsync();

            foreach (var item in news)
            {
                // Удаляем всякие теги из текста
                item.NewsBody = item.NewsBody.DeleteTags();
            }

            IndexViewModel model = new IndexViewModel()
            {
                News = news,
                Topics = topics,
                Galleries = galleries
            };

            return View(model);
        }
        #endregion

        #region 404(Page Not Found)
        public IActionResult PageNotFound()
        {
            ViewBag.Title = "Ошибка 404";

            return View();
        }
        #endregion

    }
}

OPKODABbl/Controllers/PageController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Models.Account;
using OPKODABbl.Service;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OPKODABbl.Controllers
{
    public class PageController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public PageController(WebsiteContext websiteDbContext)
        {
            _websiteDB = websiteDbContext;
        }

        #region Состав гильдии
        public async Task<IActionResult> Roster()
        {
            List<User> users = await _websiteDB.Users.Include(u => u.Role).Include(u => u.CharacterClass).Where(u => u.Role.AccessLevel >= 2 && u.Name != "Administrator").OrderByDescending(u => u.Role.AccessLevel).ToListAsync();

            ViewBag.Title = "Состав гильдии ОРКОДАВЫ";

            return View(users);
        }
        #endregion

    }
}

OPKODABbl/Views/Shared/BBcodeButtonsPartial.cshtml
<div class="BBcode">
    <input class="bb_buttons" style="font-weight: bold;" type="button" value="Жирный" onclick="BBcode_1()">
    <input class="bb_buttons" style="font-style: italic;" type="button" value="Курсив" onclick="BBcode_2()">
    <input class="bb_buttons" style="text-decoration: underline;" type="button" value="Подчеркнутый" onclick="BBcode_3()">
    <br /><br />
    <input class="bb_buttons" type="button" value="Изображение" onclick="BBcode_4()">
    <input class="bb_buttons" type="button" value="Цитата" onclick="BBcode_5()">
    <br /><br />
    <input class="bb_button_paladin" type="button" onclick="BBcode_6()">
    <input class="bb_button_warrior" type="button" onclick="BBcode_7()">
    <input class="bb_button_hunter" type="button" onclick="BBcode_8()">
    <input class="bb_button_shaman" type="button" onclick="BBcode_9()">
    <input class="bb_button_rogue" type="button" onclick="BBcode_10()">
    <input class="bb_button_druid" type="button" onclick="BBcode_11()">
    <input class="bb_button_priest" type="button" onclick="BBcode_12()">
    <input class="bb_button_mage" type="button" onclick="BBcode_13()">
    <input class="bb_button_warlock" type="button" onclick="BBcode_14()">
</div>

OPKODABbl/Views/Shared/BottomPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

OPKODABbl/Views/Shared/HeaderPartial.cshtml
@{
    string controllerName = ViewContext.HttpContext.Request.RouteValues["controller"].ToString();
}

<div class="login_header">
    @if (User.Identity.IsAuthenticated)
    {
        <form class="login_pass" asp-action="Logout" asp-controller="Account">
            @if (User.Identity.IsAuthenticated)
            {
                @if (User.IsInRole("admin"))
                {
                    <a asp-action="Index" asp-controller="Home" asp-area="Admin">Админка (черновик)</a>
                }
                <a class="login_white" asp-action="EditProfile" asp-controller="Account" asp-route-userName="@User.Identity.Name">@User.Identity.Name</a>
            }
            <input class="logout_button" type="submit" value="Выйти" />
        </form>
    }
    else
    {
        <form class="login_pass" asp-action="Login" asp-controller="Account" asp-route-ReturnUrl="@Url.PageLink()" asp-antiforgery="true" method="post">
            <img src="~/images/login_icon.png" />
            <input type="text" placeholder="Логин" class="login_pass" name="Name" required minlength="4" />
            <img src="~/images/pass_icon.png" />
            <input type="password" placeholder="Пароль" class="login_pass" name="Password" required minlength="6" />
            <input class="login_button" type="submit" value="Войти" />
            <a class="login_pass_register" asp-action="Register" asp-controller="Account">Регистрация</a>
        </form>
    }
</div>
<div class="logo"></div>
<div class="main_menu_wrapper">
    <div class="main_menu">
        <ul>
            <li><a asp-action="Index" asp-controller="Main">Главная</a></li>
            <li><a href="#">О нас</a></li>
            <li><a asp-action="Galleries" asp-controller="Gallery">Галерея</a></li>
            <li><a asp-action="Roster" asp-controller="Page">Состав</a></li>
            <li><a href="#">Вступить</a></li>
            <li><a asp-action="Index" asp-controller="Forum">Форум</a></li>
        </ul>
    </div>
    <div class="navigation">
        @*@if (!string.IsNullOrEmpty(ViewBag.NavigationTitle))
        {
            <div class="navigation_title">@ViewBag.NavigationTitle</div>
        }*@
        @if (controllerName == "News")
        {
            <div class="navigation_red"><a class="navigation_super" asp-action="NewsArchive" asp-controller="News">Архив новостей</a></div>
        }
        @if (controllerName == "Gallery")
        {
            <div class="navigation_red"><a class="navigation_super" asp-action="Galleries" asp-controller="Gallery">Галерея</a></div>
        }
        @if (controllerName == "Forum")
        {
            <div class="navigation_red"><a class="navigation_super" asp-action="Index" asp-controller="Forum">Форум</a></div>
        }
    </div>
</div>

OPKODABbl/Views/Shared/MetatagsPartial.cshtml
<meta name="viewport" content="width=device-width" />
<meta charset="utf-8" />
<title>@ViewBag.Title</title>
<link type="text/css" rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link type="text/css" rel="stylesheet" href="~/css/slider.css" asp-append-version="true" />

OPKODABbl/Views/Shared/_BBcodeScriptPartial.cshtml
<script>
    function BBcode_1() {
        document.getElementById('textarea').value += "[b][/b]"; // Добавляет к строке указанный текст
    };
    function BBcode_2() {
        document.getElementById('textarea').value += "[i][/i]"; // Добавляет к строке указанный текст
    };
    function BBcode_3() {
        document.getElementById('textarea').value += "[u][/u]"; // Добавляет к строке указанный текст
    };
    function BBcode_4() {
        document.getElementById('textarea').value += "[img][/img]"; // Добавляет к строке указанный текст
    };
    function BBcode_5() {
        document.getElementById('textarea').value += "[quote][/quote]"; // Добавляет к строке указанный текст
    };
    function BBcode_6() {
        document.getElementById('textarea').value += "[color=paladin][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_7() {
        document.getElementById('textarea').value += "[color=warrior][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_8() {
        document.getElementById('textarea').value += "[color=hunter][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_9() {
        document.getElementById('textarea').value += "[color=shaman][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_10() {
        document.getElementById('textarea').value += "[color=rogue][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_11() {
        document.getElementById('textarea').value += "[color=druid][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_12() {
        document.getElementById('textarea').value += "[color=priest][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_13() {
        document.getElementById('textarea').value += "[color=mage][/color]"; // Добавляет к строке указанный текст
    };
    function BBcode_14() {
        document.getElementById('textarea').value += "[color=warlock][/color]"; // Добавляет к строке указанный текст
    };
</script>

OPKODABbl/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>

    @await Html.PartialAsync("MetatagsPartial")

</head>
<body>

    <table class="body">
        <tr>
            <td class="renderbody">
                @await Html.PartialAsync("HeaderPartial")


                <div class="renderbody">
                    @RenderBody()
                </div>
            </td>
        </tr>
        <tr>
            <td class="bottom">
                <div class="bottom">
                    blablabla copyright i vse takoe...
                </div>
            </td>
        </tr>
    </table>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @RenderSection("Scripts", required: false)


</body>
</html>

OPKODABbl/Views/Shared/_SliderScriptPartial.cshtml
<script src="~/js/slider.js"></script>