OPKODABbl/Models/Main/News.cs
using System;
using System.Collections.Generic;

namespace OPKODABbl.Models.Main
{
    public class News
    {
        public Guid Id { get; set; }
        public string NewsTitle { get; set; }
        public string NewsBody { get; set; }
        public DateTime NewsDate { get; set; }
        public string NewsUserName { get; set; }
        public List<NewsImage> NewsImages { get; set; }
    }
}

OPKODABbl/Models/Main/NewsImage.cs
using System;

namespace OPKODABbl.Models.Main
{
    public class NewsImage
    {
        public Guid Id { get; set; }
        public string ImageName { get; set; }
        public string ImagePathOriginal { get; set; }
        public string ImagePathScaled { get; set; }
        public DateTime ImageDate { get; set; }
        public Guid NewsId { get; set; }
        public News News { get; set; }
    }
}

OPKODABbl/Models/Main/SettingsNews.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OPKODABbl.Models.Main
{
    public class SettingsNews
    {
        public Guid Id { get; set; }
        public int MaxImageSize { get; set; }
        public int ImageResizeQuality { get; set; }
    }
}

OPKODABbl/ViewModels/Main/IndexViewModel.cs
using OPKODABbl.Models.Forum;
using System.Collections.Generic;

namespace OPKODABbl.ViewModels.Main
{
    public class IndexViewModel
    {
        public List<Models.Main.News> News { get; set; }
        public List<Topic> Topics { get; set; }
        public List<Models.Gallery.Gallery> Galleries { get; set; }
    }
}

OPKODABbl/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Helpers;
using OPKODABbl.Models.Account;
using OPKODABbl.Models.Forum;
using OPKODABbl.Service;
using OPKODABbl.ViewModels.Forum;

namespace OPKODABbl.Controllers
{
    public class ForumController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public ForumController(WebsiteContext websiteContext)
        {
            _websiteDB = websiteContext;
        }

        #region Главная страница форума
        public async Task<IActionResult> Index()
        {
            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            // Формируем список разделов в соответствии с уровнем доступа юзера, включая подраздела, последние темы и сообщения в нём
            List<Section> sections = await _websiteDB.Sections.Where(s => s.SectionAccessLevel <= userAccessLevel)
                                                              .Include(s => s.Subsections).ThenInclude(s => s.Topics).ThenInclude(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                              .OrderBy(s => s.SectionPosition).ToListAsync();

            // Придется прибегнуть к такому говнокоду для разгрузки страницы Index от кода рпи формировании
            foreach (var section in sections)
            {
                foreach (var subsection in section.Subsections)
                {
                    foreach (var topic in subsection.Topics)
                    {
                        // Упорядочиваем все ответы в теме по дате
                        topic.Replies = topic.Replies.OrderBy(r => r.ReplyDate).ToList();
                    }

                    // Упорядочиваем все темы в разделе по дате последнего ответа (ответы уже упорядочили выше)
                    subsection.Topics = subsection.Topics.OrderBy(t => t.Replies.Last().ReplyDate).ToList();
                }
            }

            // Передаем в представление
            return View(sections);
        }
        #endregion

        #region Просмотр подраздела форума
        public async Task<IActionResult> Subsection(Guid subsectionId, int page = 1)
        {
            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            // Формируем модель подраздела с проверкой уровня доступа, а так же со всеми темами, находящимися в подразделе и пр.
            Subsection subsection = await _websiteDB.Subsections.Where(s => s.Section.SectionAccessLevel <= userAccessLevel)
                                                                .Include(s => s.Topics).ThenInclude(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                                .FirstOrDefaultAsync(s => s.Id == subsectionId);

            // Проверяем существование подраздела в общем и для данного пользователя в частности (при недостатке прав он будет равен null)
            if (subsection != null)
            {
                // Берем настройки из БД
                SettingsForum settings = await _websiteDB.SettingsForum.FirstAsync();

                // Сортировка ответов в каждой теме по дате
                subsection.Topics.ForEach(t => t.Replies = t.Replies.OrderBy(r => r.ReplyDate).ToList());
                // Сортировка тем в подразделе по дате последнего ответа и разбив по страницам
                int count = subsection.Topics.Count();
                int subsectionPageSize = settings.SubsectionPageSize;
                int topicPageSize = settings.TopicPageSize;

                subsection.Topics = subsection.Topics.OrderByDescending(t => t.Announcement).ThenByDescending(t => t.Replies.Last().ReplyDate).Skip((page - 1) * subsectionPageSize).Take(subsectionPageSize).ToList();

                ViewBag.TotalPages = (int)Math.Ceiling(count / (double)subsectionPageSize);
                ViewBag.CurrentPage = page;
                ViewBag.TopicPageSize = topicPageSize;

                // Передаем в представление
                return View(subsection);
            }

            // Если такого раздела не существует или у пользователя нет прав на просмотр подраздела, отправляем ему ошибку 404
            return Redirect("/Main/PageNotFound");
        }
        #endregion

        #region Просмотр топика
        public async Task<IActionResult> ViewTopic(Guid topicId, int page = 1)
        {
            // Уровень доступа пользователя по умолчанию
            int userAccessLevel = 1;

            // Если пользователь аутентифицирован, у него может оказаться более высокий уровень доступа
            if (User.Identity.IsAuthenticated)
            {
                User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);
                if (user != null)
                {
                    // Устанавливаем уровень доступа для авторизированного пользователя
                    userAccessLevel = user.Role.AccessLevel;
                }
            }

            // Формируем модель топика со всеми ответами и пользователями в нём. И обязательно проверка на уровень доступа пользователя, для избежания неавторизованного просмотра по прямой ссылке
            Topic topic = await _websiteDB.Topics.Where(t => t.Subsection.Section.SectionAccessLevel <= userAccessLevel)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.AvatarImage)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.Role)
                                                 .Include(t => t.Replies).ThenInclude(r => r.User).ThenInclude(u => u.CharacterClass)
                                                 .Include(t => t.Subsection)
                                                 .FirstOrDefaultAsync(t => t.Id == topicId);

            // Если у юзера недостаточно прав для просмотра, то топик будет null
            if (topic != null)
            {
                topic.Views += 1;
                _websiteDB.Topics.Update(topic);
                await _websiteDB.SaveChangesAsync();

                // Берем настройки из БД
                SettingsForum settings = await _websiteDB.SettingsForum.FirstAsync();

                // Разбиваем ответы по страницам
                int count = topic.Replies.Count();
                int pageSize = settings.TopicPageSize;

                topic.Replies = topic.Replies.OrderBy(r => r.ReplyDate).Skip((page - 1) * pageSize).Take(pageSize).ToList();
                // Замена символов и ББ-код в каждом ответе
                topic.Replies.ForEach(r => r.ReplyBody = r.ReplyBody.Replace(r.ReplyBody, r.ReplyBody.SpecSymbolsToView().BbCode()));

                ViewBag.TotalPages = (int)Math.Ceiling(count / (double)pageSize);
                ViewBag.CurrentPage = page;

                return View(topic);
            }

            // Если топик не существует для пользователя, выводим сообщение об ошибке
            return Redirect("/Main/PageNotFound");
        }
        #endregion

        #region Создать топик[GET]
        [HttpGet]
        public async Task<IActionResult> CreateTopic(Guid subsectionId)
        {
            // Проверка, чтобы пользователь был авторизован
            if (User.Identity.IsAuthenticated)
            {
                // Формируем модель подраздела
                Subsection subsection = await _websiteDB.Subsections.Include(s => s.Section).FirstOrDefaultAsync(s => s.Id == subsectionId);

                // Проверяем, что такой подраздел существует
                if (subsection != null)
                {
                    ViewBag.SubsectionId = subsection.Id;
                    ViewBag.SubsectionName = subsection.SubsectionName;

                    // Формируем модель пользователя с уровнем доступа для проверки
                    User user = await _websiteDB.Users.Include(u => u.Role).FirstOrDefaultAsync(u => u.Name == User.Identity.Name);

                    // Проверяем, может ли пользователь просматривать данный подраздел
                    if (subsection.Section.SectionAccessLevel <= user.Role.AccessLevel)
                    {
                        // Если может, то возвращаем ему представление
                        //ViewBag.SubsectionId = subsection.Id;
                        return View();
                    }
                }

                // А если не может, то возвращаем ему ошибку 404
                return Redirect("/Main/PageNotFound");
            }

            // Если юзер не авторизован, перенаправляем его на страницу авторизации
            return RedirectToAction("Login", "Account");
        }
        #endregion

OPKODABbl/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Models.Gallery;
using OPKODABbl.Service;

namespace OPKODABbl.Controllers
{
    public class GalleryController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public GalleryController(WebsiteContext context)
        {
            _websiteDB = context;
        }

        #region Список галерей
        public async Task<IActionResult> Galleries()
        {
            List<Gallery> galleries = await _websiteDB.Galleries.Include(g => g.GalleryImages).OrderByDescending(g => g.GalleryDate).ToListAsync();

            ViewBag.Title = "Галерея";

            return View(galleries);
        }
        #endregion

        #region Просмотр галереи
        public async Task<IActionResult> ViewGallery(Guid galleryId)
        {
            Gallery gallery = await _websiteDB.Galleries.Include(g => g.GalleryImages).FirstOrDefaultAsync(g => g.Id == galleryId);

            if (gallery != null)
            {
                ViewBag.Title = gallery.GalleryTitle;

                gallery.GalleryImages = gallery.GalleryImages.OrderBy(i => i.ImageDate).ToList();

                // Урезание заголовка до 40 символов
                if (gallery.GalleryTitle.Length > 40)
                {
                    // Ограничиваем длину заголовка и всё что сверх меры - переносим на новую отдельную строку
                    string shortTitle = new string(gallery.GalleryTitle.Take(40).ToArray()) + "...";
                    string titleOverflow = "..." + new string(gallery.GalleryTitle.Skip(40).ToArray()) + "<br /><br />";

                    gallery.GalleryTitle = shortTitle;
                    gallery.GalleryDescription = titleOverflow + gallery.GalleryDescription;

                    // Возврат записи в преобразованном виде
                    return View(gallery);
                }

                // Или в изначальном виде
                return View(gallery);
            }

            return Redirect("/Main/PageNotFound");

        }
        #endregion

    }
}

OPKODABbl/Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OPKODABbl.Helpers;
using OPKODABbl.Models.Main;
using OPKODABbl.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OPKODABbl.Controllers
{
    public class NewsController : Controller
    {
        private readonly WebsiteContext _websiteDB;

        public NewsController(WebsiteContext context)
        {
            _websiteDB = context;
        }

        #region Читать новость
        public async Task<IActionResult> ReadNews(Guid newsId)
        {
            // Ищем такую запись в БД по Id
            News news = await _websiteDB.News.Include(n => n.NewsImages).FirstOrDefaultAsync(n => n.Id == newsId);

            // Проверяем, существует ли такая запись в БД
            if (news != null)
            {
                ViewBag.Title = news.NewsTitle;

                int newsTitleLength = 50;
                // Если длина заголовка больше отображаемого лимита
                if (news.NewsTitle.Length > newsTitleLength)
                {
                    // Ограничиваем длину заголовка и всё что сверх меры - переносим на новую отдельную строку
                    string shortTitle = new string(news.NewsTitle.Take(newsTitleLength).ToArray()) + "...";
                    string titleOverflow = "..." + new string(news.NewsTitle.Skip(newsTitleLength).ToArray()) + "<br /><br />";

                    news.NewsTitle = shortTitle;
                    news.NewsBody = titleOverflow + news.NewsBody;

                    // Возврат записи в преобразованном виде
                    return View(news);
                }

                // Или в изначальном виде
                return View(news);
            }

            // Возврат ошибки 404, если запись не найдена
            return Redirect("/Main/PageNotFound");
        }
        #endregion

        #region Архив новостей
        public async Task<IActionResult> NewsArchive()
        {
            List<News> news = await _websiteDB.News.Include(n => n.NewsImages).OrderByDescending(n => n.NewsDate).ToListAsync();

            ViewBag.Title = "Архив новостей";

            // Удаляем лишние теги из текста
            foreach (var item in news)
            {
                item.NewsBody = item.NewsBody.DeleteTags();
            }

            return View(news);
        }
        #endregion

    }
}

OPKODABbl/Views/Main/AccessDenied.cshtml
<br />
<br />
<br />
<center>
    <font face="Verdana" color="#ffffff" size="50">
        403
        <br /><br />
        Недостаточно прав для просмотра страницы
    </font>
</center>

OPKODABbl/Views/Main/Index.cshtml
@using OPKODABbl.Helpers
@model OPKODABbl.ViewModels.Main.IndexViewModel

@{
    int newsPosition = 0;
}

@foreach (var news in Model.News)
{
    if (newsPosition == 0)
    {
        <div class="news0">
            @if (news.NewsImages.Count > 0)
            {
                <img class="news_img" src="@news.NewsImages.OrderBy(i => i.ImageDate).FirstOrDefault(i => i.NewsId == news.Id).ImagePathScaled" />
            }
            else
            {
                <img class="news_img" src="/images/news_noimage.jpg" />
            }
            <div class="news_img_border"><span class="news_date">@news.NewsDate.ToShortDateString()</span></div>
            <span class="news_title">@news.NewsTitle</span>
            <span class="news_body">
                @news.NewsBody
            </span>
            <div class="news_comments">Читать дальше >>></div>
            <a asp-action="ReadNews" asp-controller="News" asp-route-newsId="@news.Id"></a>
        </div>
        newsPosition++;
    }
    else
    {
        <div class="news1">
            @if (news.NewsImages.Count > 0)
            {
                <img class="news_img" src="@news.NewsImages.OrderBy(i => i.ImageDate).FirstOrDefault(i => i.NewsId == news.Id).ImagePathScaled" />
            }
            else
            {
                <img class="news_img" src="/images/news_noimage.jpg" />
            }
            <div class="news_img_border"><span class="news_date">@news.NewsDate.ToShortDateString()</span></div>
            <span class="news_title">@news.NewsTitle</span>
            <span class="news_body">
                @news.NewsBody
            </span>
            <div class="news_comments">Читать дальше >>></div>
            <a asp-action="ReadNews" asp-controller="News" asp-route-newsId="@news.Id"></a>
        </div>
    }
}

<div class="spacer_link"><a asp-action="NewsArchive" asp-controller="News">Архив новостей</a></div>

@foreach (var topic in Model.Topics)
{
    // Формирование ссылки на последнее сообщение в подразделе
    string lastMessageLink = $"/Forum/ViewTopic?topicId={topic.Id}&page={(int)Math.Ceiling(topic.Replies.Count() / (double)10)}#{topic.Replies.Count()}";

    <div class="forum_last_messages">
        @if (topic.Announcement)
        {
            <img class="forum_last_messages_icon" src="~/images/forum_announcement_icon_big.png" />
        }
        else
        {
            <img class="forum_last_messages_icon" src="~/images/forum_topic_icon_big.png" />
        }
        <a class="forum_last_messages_title" asp-action="ViewTopic" asp-controller="Forum" asp-route-topicId="@topic.Id">@topic.TopicName</a>
        <span class="forum_last_messages_message">@topic.Replies.First().ReplyBody</span>
        <span class="forum_last_messages_nickname" style="color: @topic.Replies.Last().User.CharacterClass.ClassColor;">@topic.Replies.Last().User.Name</span>
        <span class="forum_last_messages_date">@topic.Replies.Last().ReplyDate.ToShortDateString() - @topic.Replies.Last().ReplyDate.ToShortTimeString()</span>
        <a class="test_link" href="@lastMessageLink">»</a>
    </div>
}

<div class="spacer_link"><a asp-action="Index" asp-controller="Forum">Перейти на форум</a></div>

<div class="slider">
    <div class="slider__wrapper">
        @foreach (var item in Model.Galleries)
	    {
		    <div class="slider__item">
                <div class="item_title_date">
                    <div class="title_wrapper">@item.GalleryTitle</div><div class="date_wrapper">@item.GalleryDate.ToShortDateString()</div>
                </div>
                <a class="slider_link" asp-action="ViewGallery" asp-controller="Gallery" asp-route-galleryId="@item.Id"></a>
                <div style="background-image: url(@item.GallerySliderImage);"><img src="~/images/slider_border.png" /></div>
            </div>
	    }
    </div>
    <a class="slider__control slider__control_left" href="#" role="button"></a>
    <a class="slider__control slider__control_right slider__control_show" href="#" role="button"></a>
</div>

<div class="spacer_link"><a asp-action="Galleries" asp-controller="Gallery">В галерею</a></div>

@section scripts
{
    @{
        await Html.RenderPartialAsync("_SliderScriptPartial");
    }
}

OPKODABbl/Views/Main/PageNotFound.cshtml
<br /><br /><br />
<center>
    <font face="Verdana" color="#ffffff" size="50">
        404
        <br /><br />
        Запрашиваемая страница не найдена
    </font>
</center>